favicon: /img/favicon.ico

default_top_img: /img/article-bg.png
index_img: /img/site-cover.jpg
archive_img: /img/site-cover.jpg
tag_img: /img/site-cover.jpg
category_img: /img/site-cover.jpg
avatar:
  img: /img/site-avatar.png

cover:
  default_cover:
    - /img/article-bg.png

aside:
  card_author:
    button:
      enable: false
  card_announcement:
    enable: false
