favicon: /img/favicon.ico

menu:
  首页: / || fas fa-house
  文章: /archives/ || fas fa-box-archive
  标签: /tags/ || fas fa-tags
  友链: /link/ || fas fa-link
  关于我: /about/ || fas fa-user-astronaut

default_top_img: /img/article-bg.png
index_img: /img/site-cover.jpg
archive_img: /img/site-cover.jpg
tag_img: /img/site-cover.jpg
category_img: /img/site-cover.jpg
avatar:
  img: /img/site-avatar.png
  effect: false

cover:
  default_cover:
    - /img/article-bg.png
    - /img/site-cover.jpg
    - /img/cover-kurumi.png
    - /img/cover-iso.jpg

index_post_content:
  method: 1
  length: 180

subtitle:
  enable: true
  effect: true
  sub:
    - never forget your beginning

inject:
  head:
    - <link rel="stylesheet" href="/css/cyberpunk.css">
  bottom:
    - <script src="/js/avatar-click-spin.js"></script>

aside:
  card_author:
    button:
      enable: false
  card_announcement:
    enable: false
